# Generated by Django 4.1.2 on 2022-11-13 14:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blog_sections_alter_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.section_image_file_path),
        ),
    ]
