# Generated by Django 4.1.2 on 2022-11-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_section_tag_blog_sections_blog_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='user',
        ),
    ]
