---
name: Checks # github name

on: [push] # trigger

jobs: # what to do on trigger
  test-lint: # job id
    name: Test and Lint # new job, id
      runs-on: ubuntu-20.04 # linux mock runner; ubuntu ideal for project
      steps: # steps for job
        - name: Login to Docker Hub
          uses: docker/login-action@v1 # using pre made action in github repo
          with: # creds
            username: ${{ secret.DOCKERHUB_USER }}
            passwords: ${{ secret.DOCKERHUB_TOKEN }}
        - name: Checkout # provided by gh, checks our code inside gh actions job; need to use for tests and linting
          uses: actions/checkout@v2 
        - name: Test # test stage
          run: docker-compose run --rm app sh -c "python manage.py test" # runs unit tests
        - name: Lint # lint stds check
          run: docker-compose run --rm app sh -c "python manage.py flake8" # runs flake8 check